import {
  LayoutGrid,
  Store,
  List,
  ShoppingBag,
  CalendarCheck,
  Monitor,
  Truck,
  UserCog,
  Gift,
  User,
  Printer,
  BarChart3,
  Bell,
  Palette,
  ShieldCheck,
  FileText,
  Tags,
  PackagePlus,
  ClipboardList,
  AlertTriangle,
  BadgeCheck,
  BadgePercent,
  Coins,
  CreditCard,
  ReceiptText,
  Inbox,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { IconType } from "react-icons";
import { PiUsersThree } from "react-icons/pi";

export type SidebarSection = "main" | "account";
export type SidebarRole = "BUSINESS_ADMIN" | "RESTAURANT_ADMIN" | "BRANCH_ADMIN" | "STAFF";

export interface MenuItem {
  title: string;
  labelKey?: string;
  href?: string;
  icon: LucideIcon | IconType;
  section: SidebarSection;
  children?: MenuItem[];
  roles?: SidebarRole[];
  permissionAccesses?: string[];
}

const restaurantAdminRoles: SidebarRole[] = ["BUSINESS_ADMIN", "RESTAURANT_ADMIN"];
const allAdminRoles: SidebarRole[] = ["BUSINESS_ADMIN", "RESTAURANT_ADMIN", "BRANCH_ADMIN"];
const accountProfileRoles: SidebarRole[] = ["BUSINESS_ADMIN", "RESTAURANT_ADMIN", "BRANCH_ADMIN", "STAFF"];
const menuStaffRoles: SidebarRole[] = ["BUSINESS_ADMIN", "RESTAURANT_ADMIN", "BRANCH_ADMIN", "STAFF"];
const branchAdminOnly: SidebarRole[] = ["BRANCH_ADMIN"];

export const menuItems: MenuItem[] = [
  {
    title: "Dashboard",
    labelKey: "dashboard",
    href: "/",
    icon: LayoutGrid,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["dashboard"],
  },
  {
    title: "Branch Management",
    labelKey: "branchManagement",
    href: "/branches",
    icon: Store,
    section: "main",
    roles: restaurantAdminRoles,
    permissionAccesses: ["branch_management", "branch-management"],
  },
  {
    title: "My Branch",
    labelKey: "myBranch",
    href: "/branch-workspace",
    icon: Store,
    section: "main",
    roles: branchAdminOnly,
    permissionAccesses: ["branch_management", "branch-management"],
  },
  {
    title: "Menu Management",
    labelKey: "menuManagement",
    href: "/menu",
    icon: List,
    section: "main",
    roles: menuStaffRoles,
    permissionAccesses: ["menu", "menu-management", "restaurant-menus"],
    children: [
      {
        title: "Menu",
        labelKey: "menu",
        href: "/menu",
        icon: List,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["menu", "menu-management", "restaurant-menus"],
      },
      {
        title: "Categories",
        labelKey: "categories",
        href: "/menu/categories",
        icon: ClipboardList,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["menu-categories", "menu", "menu-management"],
      },
      {
        title: "Cuisines",
        labelKey: "cuisines",
        href: "/menu/cuisines",
        icon: ClipboardList,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["cuisines", "menu", "menu-management"],
      },
      {
        title: "Modifier Categories",
        labelKey: "modifierCategories",
        href: "/menu/modifier-categories",
        icon: ClipboardList,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["modifier-categories", "modifiers", "menu", "menu-management"],
      },
      {
        title: "Modifier Groups",
        labelKey: "modifierGroups",
        href: "/menu/modifier-groups",
        icon: ClipboardList,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["modifier-groups", "modifiers", "menu", "menu-management"],
      },
      {
        title: "Modifiers",
        labelKey: "modifiers",
        href: "/menu/modifier",
        icon: Tags,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["modifiers", "menu", "menu-management"],
      },
      {
        title: "Variations",
        labelKey: "variations",
        href: "/menu/variations",
        icon: ClipboardList,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["variations", "menu", "menu-management"],
      },
      {
        title: "Deals",
        labelKey: "deals",
        href: "/menu/deals",
        icon: BadgePercent,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["coupons", "promotions", "menu", "menu-management"],
      },
      {
        title: "Items",
        labelKey: "menuItems",
        href: "/menu/items",
        icon: PackagePlus,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["menu-items", "menu", "menu-management"],
      },
      {
        title: "Allergen",
        labelKey: "allergen",
        href: "/menu/allergen",
        icon: AlertTriangle,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["menu-items", "menu", "menu-management"],
      },
      {
        title: "Labels",
        labelKey: "labels",
        href: "/menu/labels",
        icon: BadgeCheck,
        section: "main",
        roles: menuStaffRoles,
        permissionAccesses: ["menu-items", "menu", "menu-management"],
      },
    ],
  },
  {
    title: "Order Management",
    labelKey: "orderManagement",
    href: "/orders",
    icon: ShoppingBag,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["orders"],
  },
  {
    title: "Table Reservations",
    labelKey: "tableReservations",
    href: "/table-reservations",
    icon: CalendarCheck,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["orders", "settings"],
  },
  {
    title: "POS Management",
    labelKey: "posManagement",
    href: "/pos",
    icon: Monitor,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["pos"],
  },
  // Inventory module is intentionally hidden for now.
  // {
  //   title: "Inventory",
  //   labelKey: "inventory",
  //   href: "/inventory",
  //   icon: PackagePlus,
  //   section: "main",
  //   roles: branchAdminOnly,
  // },
  {
    title: "Customer Management",
    labelKey: "customerManagement",
    href: "/customer-settings",
    icon: PiUsersThree,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["customers"],
  },
  {
    title: "Contact Submissions",
    labelKey: "contactSubmissions",
    href: "/contact-submissions",
    icon: Inbox,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["settings"],
  },
  {
    title: "Loyalty Program",
    labelKey: "loyaltyProgram",
    href: "/loyalty",
    icon: Coins,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["coupons", "promotions"],
  },
  {
    title: "Deliveryman",
    labelKey: "deliveryman",
    href: "/deliveryman",
    icon: Truck,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["staff-management"],
  },
  {
    title: "Employees",
    labelKey: "employees",
    href: "/employees-settings",
    icon: UserCog,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["staff-management", "staff-roles"],
  },
  {
    title: "Promotion Management",
    labelKey: "promotionManagement",
    href: "/promotion-management",
    icon: Gift,
    section: "main",
    roles: allAdminRoles,
    children: [
      {
        title: "Promotions",
        labelKey: "promotions",
        href: "/promotion-management",
        icon: Gift,
        section: "main",
        roles: restaurantAdminRoles,
        permissionAccesses: ["promotions", "coupons"],
      },
      {
        title: "Gift Cards",
        labelKey: "giftCards",
        href: "/promotion-management/gift-cards",
        icon: CreditCard,
        section: "main",
        roles: allAdminRoles,
        permissionAccesses: ["promotions", "coupons"],
      },
    ],
  },
  {
    title: "Content Management",
    labelKey: "contentManagement",
    href: "/content-management",
    icon: FileText,
    section: "main",
    roles: allAdminRoles,
    permissionAccesses: ["settings"],
    children: [
      {
        title: "Faqs",
        labelKey: "faqs",
        href: "/faqs",
        icon: FileText,
        section: "main",
        roles: restaurantAdminRoles,
        permissionAccesses: ["settings"],
      },
      {
        title: "Legal & Tax Profile",
        labelKey: "legalProfile",
        href: "/legal-profile",
        icon: ReceiptText,
        section: "main",
        roles: allAdminRoles,
        permissionAccesses: ["settings"],
      },
      {
        title: "About Us",
        labelKey: "aboutUs",
        href: "/content-management/about",
        icon: FileText,
        section: "main",
        roles: restaurantAdminRoles,
        permissionAccesses: ["settings"],
      },
      {
        title: "Privacy Policy",
        labelKey: "privacyPolicy",
        href: "/privacy-policy",
        icon: ShieldCheck,
        section: "main",
        roles: restaurantAdminRoles,
        permissionAccesses: ["settings"],
      },
    ],
  },
  {
    title: "Profile",
    labelKey: "profile",
    href: "/profile",
    icon: User,
    section: "account",
    roles: accountProfileRoles,
  },
  {
    title: "Auto-Printing / POS",
    labelKey: "autoPrintingPos",
    href: "/auto-printing",
    icon: Printer,
    section: "account",
    roles: allAdminRoles,
    permissionAccesses: ["pos"],
  },
  {
    title: "Reports & Payouts",
    labelKey: "reportsPayouts",
    href: "/reports",
    icon: BarChart3,
    section: "account",
    roles: allAdminRoles,
    permissionAccesses: ["reports"],
  },
  {
    title: "Payment Settings",
    labelKey: "paymentSettings",
    href: "/payment-settings",
    icon: CreditCard,
    section: "account",
    roles: restaurantAdminRoles,
    permissionAccesses: ["settings"],
  },

  {
    title: "Notifications",
    labelKey: "notifications",
    href: "/notifications",
    icon: Bell,
    section: "account",
    roles: allAdminRoles,
    permissionAccesses: ["chat", "settings"],
  },
  {
    title: "Storefront Settings",
    labelKey: "storefrontSettings",
    href: "/theme-settings",
    icon: Palette,
    section: "account",
    roles: restaurantAdminRoles,
    permissionAccesses: ["settings"],
  },
];
